import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F8',
  },
  content: {
    padding: 16,
  },
  headerCard: {
    borderRadius: 24,
    alignItems: 'center',
    paddingTop: 24,
    paddingBottom: 22,
    overflow: 'hidden',
    marginBottom: 16,
  },
  headerBall: {
    position: 'absolute',
    top: -30,
    right: -40,
  },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  avatarImg: {
    width: 72,
    height: 72,
    resizeMode: 'contain',
  },
  trainerName: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '900',
    marginTop: 12,
    letterSpacing: 0.3,
  },
  levelPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginTop: 8,
  },
  levelText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  summaryRow: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 18,
    paddingVertical: 16,
    marginBottom: 16,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
  },
  summaryItem: {
    flex: 1,
    alignItems: 'center',
    gap: 5,
  },
  summaryIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryValue: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1B1B1F',
  },
  summaryLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6B7280',
  },
  block: {
    marginBottom: 16,
  },
  progressCard: {
    marginBottom: 16,
    backgroundColor: '#fff',
    borderRadius: 18,
  },
  blockPad: {
    padding: 16,
  },
  blockHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  blockTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1B1B1F',
  },
  blockValue: {
    fontSize: 14,
    fontWeight: '800',
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1B1B1F',
    letterSpacing: -0.1,
  },
  sectionCount: {
    fontSize: 13,
    fontWeight: '700',
    color: '#6B7280',
  },
  teamRow: {
    gap: 14,
    paddingVertical: 2,
    paddingRight: 8,
  },
  teamItem: {
    alignItems: 'center',
    width: 72,
  },
  teamAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  teamImg: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
  },
  teamName: {
    fontSize: 11,
    fontWeight: '700',
    color: '#49454F',
    textAlign: 'center',
  },
  achCard: {
    backgroundColor: '#fff',
    marginBottom: 10,
    borderRadius: 16,
  },
  achContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 14,
  },
  achIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  achInfo: {
    flex: 1,
  },
  achTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  achTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1B1B1F',
    flex: 1,
  },
  achDone: {
    fontSize: 14,
    fontWeight: '900',
    color: '#2E9E5B',
    marginLeft: 8,
  },
  achDesc: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 8,
  },
  logoutBtn: {
    borderRadius: 14,
    borderColor: '#CC0000',
    marginTop: 4,
  },
});
