import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F8',
  },
  content: {
    padding: 16,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F5F8',
    gap: 12,
    padding: 24,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#49454F',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    marginTop: 2,
  },
  title: {
    fontSize: 24,
    fontWeight: '900',
    color: '#1B1B1F',
    letterSpacing: -0.3,
  },
  scorePill: {
    backgroundColor: '#1B1B1F',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  scoreText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 16,
  },
  scoreDim: {
    color: '#9E9E9E',
    fontWeight: '700',
  },
  fighter: {
    backgroundColor: '#fff',
    borderRadius: 18,
    borderWidth: 2,
    alignItems: 'center',
    paddingVertical: 16,
    marginBottom: 12,
    overflow: 'hidden',
  },
  myFighter: {
    marginTop: 4,
  },
  fighterBadge: {
    position: 'absolute',
    top: 0,
    left: 0,
    borderBottomRightRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  fighterBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  fighterImg: {
    width: 110,
    height: 110,
    resizeMode: 'contain',
  },
  fighterName: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1B1B1F',
    marginTop: 4,
  },
  fighterTypes: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 2,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1B1B1F',
    marginTop: 8,
    marginBottom: 12,
  },
  teamGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  teamPick: {
    width: '31%',
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 2,
    alignItems: 'center',
    paddingVertical: 10,
  },
  pickImg: {
    width: 56,
    height: 56,
    resizeMode: 'contain',
  },
  pickName: {
    fontSize: 11,
    fontWeight: '700',
    color: '#49454F',
    marginTop: 2,
  },
  pressed: {
    opacity: 0.8,
    transform: [{ scale: 0.97 }],
  },
  roundBanner: {
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    alignItems: 'center',
    gap: 4,
  },
  roundText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1B1B1F',
    textAlign: 'center',
  },
  roundValue: {
    fontWeight: '900',
  },
  roundResult: {
    fontSize: 14,
    fontWeight: '900',
  },
  attrGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  attrBtn: {
    width: '31%',
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    gap: 2,
  },
  attrUsed: {
    backgroundColor: '#ECECEF',
    elevation: 0,
  },
  attrUsedText: {
    color: '#BDBDBD',
  },
  attrLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6B7280',
  },
  attrValue: {
    fontSize: 22,
    fontWeight: '900',
    color: '#CC0000',
  },
  finalBox: {
    backgroundColor: '#fff',
    borderRadius: 18,
    alignItems: 'center',
    padding: 24,
    gap: 6,
    marginBottom: 12,
  },
  finalTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#1B1B1F',
  },
  finalScore: {
    fontSize: 16,
    fontWeight: '700',
    color: '#6B7280',
  },
  rewardBox: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#F59E0B',
  },
  rewardTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#1B1B1F',
    textAlign: 'center',
  },
  rewardSub: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 2,
    marginBottom: 14,
  },
  rewardGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  rewardPick: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 2,
    alignItems: 'center',
    paddingVertical: 12,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
  },
  claimedBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#E6F4EA',
    borderRadius: 12,
    paddingVertical: 12,
    marginBottom: 12,
  },
  claimedText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#2E9E5B',
  },
  againBtn: {
    borderRadius: 14,
    backgroundColor: '#CC0000',
    alignSelf: 'stretch',
    marginBottom: 12,
  },
  history: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    marginTop: 4,
  },
  historyTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1B1B1F',
    marginBottom: 8,
  },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#EEE',
    gap: 8,
  },
  historyIdx: {
    width: 18,
    fontSize: 11,
    fontWeight: '800',
    color: '#9E9E9E',
  },
  historyCell: {
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    color: '#1B1B1F',
  },
  historyRight: {
    textAlign: 'right',
  },
});
